### ISSUE TITLE
threema php sdk libsodium detection

### ISSUE THREAD

**Issue by medienverbinder** [rugk/threema-msgapi-sdk-php#31]
On my development system I installed libsodium. You can list the available functions of Sodium through a small script:

```
<?php

$br = (php_sapi_name() == "cli")? "":"<br>";
if(!extension_loaded('libsodium')) {
    dl('libsodium.' . PHP_SHLIB_SUFFIX);
}

$module = 'libsodium';

$functions = get_extension_funcs($module);
echo "Functions available in the test extension:$br\n";

foreach($functions as $func) {
 echo $func."$br\n";
}
echo "$br\n";

exit();

?>
```

Here are some examples:

```
...
Sodium\"increment"
Sodium\"library_version_major"
Sodium\"library_version_minor"
Sodium\"memcmp"
Sodium\"memzero"
Sodium\"version_string"
Sodium\crypto_scalarmult_base
...
```

But if I call "threema-msgapi-tool.php" via console the sodium test fails.

```
Threema PHP MsgApi Tool
Version: 1.1.5
CryptTool: Salt Pure PHP implementation, please try to install and use the libsodium PHP extension
for a better performance
```

I think the version detection for Sodium extension only works under certain prerequisite (options during compilation) .... but i just do not know which?

**Comment by rugk** [comment]
As for the check for newer libsodium versions [it checks whether the extension is loaded and the `sodium_version_string` function does _not_ exist](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptToolSodium.php#L112-L115), which is called from [here](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptTool.php#L68).

I also see in your code snippet above that you check whether libsodium is loaded and load with with `dl` if not. Possibly this is the issue, because the SDK does not do this AFAIK. So adding these three lines to the bootstrap.php may fix the problem.
Or even better: Get libsodium to autoload when the webserver starts.

PS: On GitHub you can syntax-highlight code snippets in markdown [like this](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting).

**Comment by medienverbinder** [comment]
Thanks for the tip and your quick response.
I think the version string was replaced days ago. 

=> https://github.com/paragonie/libsodium-php/commit/c270720c2be301a762c216b326f7639b945f9f3a

```
-$function = 'sodium_version_string';
+$function = '\Sodium\version_string';
```

and I use the latest version.
I have to look at that again :-)

**Comment by medienverbinder** [comment]
But what is the difference between these two methods ?

```
sodium_version_string
```

https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptToolSodium.php#L112-L115

and 

```
\Sodium\version_string
```

https://github.com/rugk/threema-msgapi-sdk-php/blob/master/source/Threema/MsgApi/Tools/CryptToolSodium.php#L141-L144

**Comment by rugk** [comment]
`sodium_version_string` is the old version used by the old versions of libsodium. That's why it is also checked that this method does _not_ exist when using the new libsodium (>=0.2.0):

``` php
false === method_exists('Sodium', 'sodium_version_string');
```

[`\Sodium\version_string`](https://paragonie.com/book/pecl-libsodium/read/03-utilities-helpers.md#version) is the actual (new) class which returns the version of Sodium.

**Comment by rugk** [comment]
In case it helps here is a small debug script: https://gist.github.com/rugk/eae69ad07042a1d51d57

**Comment by medienverbinder** [comment]
Thanks!
Here are the results:

```
libsodium is loaded<br/>you use a recent version of libsodium<br/>
Fatal error: Call to undefined function Sodium\version_string() in /home/testscript/check.php on line 15
```

Here's another option (Linux/Unix):

```
php -i | grep sodium
```

Results:

```
libsodium
libsodium support => enabled
libsodium headers version => 1.0.8
libsodium library version => 1.0.8
```

The libraries are installed, but the method "\Sodium\version_string" is not available.

**Comment by rugk** [comment]
> The libraries are installed, but the method "\Sodium\version_string" is not available. 

Indeed it seems like this. But in your first test script the method "version_string" is mentioned...
I've open an issue at [libsodium-php](https://github.com/jedisct1/libsodium-php/issues/79). It may be an issue of Sodium 1.0.8.

**Comment by medienverbinder** [comment]
Found a mistake when compiling libsodium-php. On my development environment an older PHP version was deposited for the php-cli (5.4.11). On my LAMP stack with PHP version 5.6 for this reason the libsodium library could not be loaded correctly. With the compilation of libsodium-php and php 5.6 now everything is running normally and your detection script works correctly.

Output Threema SDK:

```
 Threema PHP MsgApi Tool
 Version: 1.1.5
 CryptTool: sodium Sodium implementation 1.0.8
```

Output of your detection script:

```
libsodium is loaded
you use a recent version of libsodium
Sodium version: 1.0.8
```

Thanks for your help!

Regards

**Comment by rugk** [comment]
Nice to hear.
